services:
  - type: web
    name: community-service-api
    env: node
    plan: free
    buildCommand: cd frontend-angular && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
